package com.blert.events;

public enum EventType {
    RAID_START,
    RAID_END,
    RAID_UPDATE,
    ROOM_STATUS,
    PLAYER_UPDATE,
    PLAYER_ATTACK,
    PLAYER_DEATH,
    NPC_UPDATE,

    MAIDEN_CRAB_SPAWN,
    MAIDEN_CRAB_LEAK,
    MAIDEN_BLOOD_SPLATS,

    BLOAT_DOWN,
    BLOAT_UP,

    NYLO_WAVE_SPAWN,
    NYLO_WAVE_STALL,
    NYLO_CLEANUP_END,
    NYLO_BOSS_SPAWN,

    SOTE_MAZE_PROC,
    SOTE_MAZE_PATH,

    XARPUS_PHASE,
}
